slice_name: "Resumen \xB7 Interior"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  viz_type: big_number_total
  metric: sum_tendencia
  adhoc_filters:
  - expressionType: SIMPLE
    subject: grupo
    operator: ==
    comparator: INTERIOR
    clause: WHERE
    isExtra: false
  subheader: Interior
  datasource: 1__table
  header_font_size: 0.3
  subheader_font_size: 0.125
query_context: null
cache_timeout: null
uuid: b2ff5340-9f89-428f-95d1-2e4399591773
version: 1.0.0
dataset_uuid: bf938b71-2cce-4dfd-87e6-e4425d8caeb9
