slice_name: "Resumen \xB7 Casa Central"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  viz_type: big_number_total
  metric: sum_tendencia
  adhoc_filters:
  - expressionType: SIMPLE
    subject: grupo
    operator: ==
    comparator: CASA CENTRAL
    clause: WHERE
    isExtra: false
  subheader: Casa Central
  datasource: 1__table
  header_font_size: 0.3
  subheader_font_size: 0.125
query_context: null
cache_timeout: null
uuid: 883c7e3d-afca-4263-8796-1eaeb785dac4
version: 1.0.0
dataset_uuid: bf938b71-2cce-4dfd-87e6-e4425d8caeb9
