slice_name: "\U0001F7E2 Cubierto (VERDE \xB7 >30 d\xEDas)"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 3__table
  viz_type: big_number_total
  metric: count_articulos
  y_axis_format: ',d'
  adhoc_filters:
  - expressionType: SIMPLE
    subject: estado_semaforo
    operator: ==
    comparator: VERDE
    clause: WHERE
    isExtra: false
    isNew: false
query_context: null
cache_timeout: null
uuid: fb9bdbfd-8930-48e5-b946-55e682e2acdf
version: 1.0.0
dataset_uuid: 6b1c34b7-564d-4dc2-88a7-2c1fb69a90df
