slice_name: "\U0001F7E1 Vigilar (AMARILLO \xB7 15-30 d\xEDas)"
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 3__table
  viz_type: big_number_total
  metric: count_articulos
  y_axis_format: ',d'
  adhoc_filters:
  - expressionType: SIMPLE
    subject: estado_semaforo
    operator: ==
    comparator: AMARILLO
    clause: WHERE
    isExtra: false
    isNew: false
query_context: null
cache_timeout: null
uuid: 1d56b760-5c49-4f51-91e7-562e8634d566
version: 1.0.0
dataset_uuid: 6b1c34b7-564d-4dc2-88a7-2c1fb69a90df
